[package]
name        = "valence-domain-clients"
authors    = ["Timewave Labs"]
edition    = "2021"
license    = "Apache-2.0"
version    = "0.1.0"
repository = "https://github.com/timewave-computer/valence-domain-clients"
description = "Client implementations for interacting with Valence Protocol domains"

[workspace]
members = [
    "crates/core",
    "crates/evm",
    "crates/cosmos",
    "crates/proto",
    "crates/coprocessor",
    "examples",
    "."
]
resolver = "2"

[features]
# EVM chains
ethereum = ["valence-evm/ethereum"]
base = ["valence-evm/base"]

# Cosmos chains
babylon = ["valence-cosmos/babylon"]
noble = ["valence-cosmos/noble"]
gaia = ["valence-cosmos/gaia"]
neutron = ["valence-cosmos/neutron"]
osmosis = ["valence-cosmos/osmosis"]

# Coprocessor support
coprocessor = ["valence-coprocessor-client"]

# Default features set - all functionality available
default = ["ethereum", "base", "babylon", "gaia", "neutron", "osmosis", "noble", "coprocessor"]

[dependencies]
# Internal workspace crates
valence-core = { path = "crates/core", version = "0.1.0" }
valence-evm = { path = "crates/evm", version = "0.1.0" }
valence-cosmos = { path = "crates/cosmos", version = "0.1.0" }
valence-proto = { path = "crates/proto", version = "0.1.0" }
valence-coprocessor-client = { path = "crates/coprocessor", version = "0.1.0", optional = true }

# Re-export dependencies needed for the main crate
tokio = { version = "1.35.1", features = ["full"] }
async-trait = "0.1.74"

[dev-dependencies]
mockall = "0.12.1"
once_cell = "1.19.0"
rand = "0.8.5"
hex = "0.4.3"
tempfile = "3.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cosmos-sdk-proto = "0.20.0"
anyhow = "1.0.83"
clap = { version = "4.4.8", features = ["derive"] }

[lib]
name = "valence_domain_clients"
path = "src/lib.rs"

[build-dependencies]
tonic-build = { version = "0.12.1", default-features = false, features = ["prost", "transport"] }

[[example]]
name = "coprocessor_client"
path = "examples/coprocessor_client.rs"
