# Controls the maximum width of lines.
max_width = 85

# Use Unix-style line endings (\n).
newline_style = "Unix"

# How to indent.
hard_tabs = false
tab_spaces = 4

# Whether to reorder imports.
reorder_imports = true

# Whether to reorder 'mod' declarations.
reorder_modules = true

# Whether to remove nested parentheses where applicable.
remove_nested_parens = true